package com.kington.fshg.common.sms.zgyd;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * Service service = new Service();
 * ServiceSoap portType = service.getServiceSoap();
 * portType.clientForDCM(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "Service", targetNamespace = "http://Gmcc.SiniOA.Com/", wsdlLocation = "http://dcm.sinioa.com/ClientForDCM.asmx?WSDL")
public class Service extends javax.xml.ws.Service {

	private final static URL SERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.kington.fshg.common.sms.zgyd.Service.class
			.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.kington.fshg.common.sms.zgyd.Service.class.getResource(".");
			url = new URL(baseUrl,
					"http://dcm.sinioa.com/ClientForDCM.asmx?WSDL");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://dcm.sinioa.com/ClientForDCM.asmx?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SERVICE_WSDL_LOCATION = url;
	}

	public Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Service() {
		super(SERVICE_WSDL_LOCATION, new QName("http://Gmcc.SiniOA.Com/",
				"Service"));
	}

	/**
	 * 
	 * @return returns ServiceSoap
	 */
	@WebEndpoint(name = "ServiceSoap")
	public ServiceSoap getServiceSoap() {
		return super.getPort(
				new QName("http://Gmcc.SiniOA.Com/", "ServiceSoap"),
				ServiceSoap.class);
	}

	/**
	 * 
	 * @return returns ServiceSoap
	 */
	@WebEndpoint(name = "ServiceSoap12")
	public ServiceSoap getServiceSoap12() {
		return super.getPort(new QName("http://Gmcc.SiniOA.Com/",
				"ServiceSoap12"), ServiceSoap.class);
	}

}
